version: '3.8'
services:
  web_app:
    container_name: httpx_laravel
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:80"
    volumes:
      - .:/var/app
    environment:
      DB_HOST: db
      DB_DATABASE: local
      DB_USERNAME: admin
      DB_PASSWORD: password
  db:
    container_name: httpx_db
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: local
      MYSQL_USER: admin
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - dbdata:/var/lib/mysql
volumes:
  dbdata:
